insert into  states (code,name,created_at,updated_at) values ('AL','Alabama',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('AK','Alaska',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('AS','American Samoa',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('AZ','Arizona',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('AR','Arkansas',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('CA','California',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('CO','Colorado',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('CT','Connecticut',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('DE','Delaware',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('DC','District of Columbia',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('FM','Federated States of Micronesia',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('FL','Florida',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('GA','Georgia',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('GU','Guam',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('HI','Hawaii',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('ID','Idaho',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('IL','Illinois',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('IN','Indiana',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('IA','Iowa',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('KS','Kansas',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('KY','Kentucky',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('LA','Louisiana',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('ME','Maine',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MH','Marshall Islands',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MD','Maryland',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MA','Massachusetts',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MI','Michigan',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MN','Minnesota',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MS','Mississippi',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MO','Missouri',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MT','Montana',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('NE','Nebraska',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('NV','Nevada',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('NH','New Hampshire',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('NJ','New Jersey',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('NM','New Mexico',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('NY','New York',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('NC','North Carolina',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('ND','North Dakota',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('MP','Northern Mariana Islands',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('OH','Ohio',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('OK','Oklahoma',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('OR','Oregon',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('PW','Palau',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('PA','Pennsylvania',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('PR','Puerto Rico',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('RI','Rhode Island',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('SC','South Carolina',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('SD','South Dakota',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('TN','Tennessee',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('TX','Texas',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('UT','Utah',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('VT','Vermont',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('VI','Virgin Islands',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('VA','Virginia',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('WA','Washington',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('WV','West Virginia',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('WI','Wisconsin',NOW(),NOW());
insert into  states (code,name,created_at,updated_at) values ('WY','Wyoming',NOW(),NOW());